"""Type stubs for adk_rust"""

from typing import Any, Awaitable, Callable, Dict, List, Optional

# Types
class Content:
    role: str
    parts: List[Part]

    def __init__(self, role: str = "user") -> None: ...
    @staticmethod
    def user(text: str) -> Content: ...
    @staticmethod
    def model(text: str) -> Content: ...
    def with_text(self, text: str) -> Content: ...
    def get_text(self) -> Optional[str]: ...

class Part:
    @staticmethod
    def text(text: str) -> Part: ...
    def get_text(self) -> Optional[str]: ...
    def is_text(self) -> bool: ...
    def is_function_call(self) -> bool: ...

class Event:
    id: str
    author: str
    def content(self) -> Optional[Content]: ...
    def get_text(self) -> Optional[str]: ...
    def get_state_delta(self) -> Dict[str, Any]: ...
    def transfer_to_agent(self) -> Optional[str]: ...

# Models
class GeminiModel:
    def __init__(self, api_key: str, model: str = "gemini-2.5-flash") -> None: ...
    @property
    def name(self) -> str: ...

class OpenAIModel:
    def __init__(self, api_key: str, model: str = "gpt-4o") -> None: ...
    @staticmethod
    def compatible(api_key: str, base_url: str, model: str) -> OpenAIModel: ...
    @property
    def name(self) -> str: ...

class AnthropicModel:
    def __init__(self, api_key: str, model: str = "claude-sonnet-4-20250514") -> None: ...
    @staticmethod
    def from_api_key(api_key: str) -> AnthropicModel: ...
    @property
    def name(self) -> str: ...

class DeepSeekModel:
    def __init__(self, api_key: str, model: str) -> None: ...
    @staticmethod
    def chat(api_key: str) -> DeepSeekModel: ...
    @staticmethod
    def reasoner(api_key: str) -> DeepSeekModel: ...
    @property
    def name(self) -> str: ...

class GroqModel:
    def __init__(self, api_key: str, model: str) -> None: ...
    @staticmethod
    def llama70b(api_key: str) -> GroqModel: ...
    @staticmethod
    def llama8b(api_key: str) -> GroqModel: ...
    @staticmethod
    def mixtral(api_key: str) -> GroqModel: ...
    @property
    def name(self) -> str: ...

class OllamaModel:
    def __init__(self, model: str) -> None: ...
    @staticmethod
    def with_host(host: str, model: str) -> OllamaModel: ...
    @property
    def name(self) -> str: ...

class MockLlm:
    def __init__(self, name: str, response_text: str = "Mock response") -> None: ...
    @property
    def name(self) -> str: ...

# Agents
class LlmAgentBuilder:
    def __init__(self, name: str) -> None: ...
    def description(self, desc: str) -> LlmAgentBuilder: ...
    def instruction(self, instruction: str) -> LlmAgentBuilder: ...
    def model(self, model: Any) -> LlmAgentBuilder: ...
    def tool(self, tool: FunctionTool) -> LlmAgentBuilder: ...
    def sub_agent(self, agent: LlmAgent) -> LlmAgentBuilder: ...
    def output_key(self, key: str) -> LlmAgentBuilder: ...
    def build(self) -> LlmAgent: ...

class LlmAgent:
    @staticmethod
    def builder(name: str) -> LlmAgentBuilder: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...

class CustomAgent:
    def __init__(self, name: str, description: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...

class SequentialAgent:
    def __init__(self, name: str, agents: List[LlmAgent]) -> None: ...
    @property
    def name(self) -> str: ...

class ParallelAgent:
    def __init__(self, name: str, agents: List[LlmAgent]) -> None: ...
    @property
    def name(self) -> str: ...

class LoopAgent:
    def __init__(self, name: str, agents: List[LlmAgent], max_iterations: int = 10) -> None: ...
    @property
    def name(self) -> str: ...

# Tools
class FunctionTool:
    def __init__(
        self,
        name: str,
        description: str,
        handler: Callable[[Any, Dict[str, Any]], Any],
        parameters_schema: Optional[Dict[str, Any]] = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...

class BasicToolset:
    def __init__(self, name: str) -> None: ...
    def add(self, tool: FunctionTool) -> None: ...
    def tools(self) -> List[FunctionTool]: ...
    @property
    def name(self) -> str: ...
    def __len__(self) -> int: ...

class ExitLoopTool:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...

class LoadArtifactsTool:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...

class GoogleSearchTool:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...

# Session
class InMemorySessionService:
    def __init__(self) -> None: ...

class State:
    def __init__(self) -> None: ...
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def all(self) -> Dict[str, Any]: ...
    def contains(self, key: str) -> bool: ...
    def remove(self, key: str) -> bool: ...

class StreamingMode:
    None_: StreamingMode
    SSE: StreamingMode
    Bidi: StreamingMode

class RunConfig:
    def __init__(self, streaming_mode: StreamingMode = ...) -> None: ...
    @property
    def streaming_mode(self) -> StreamingMode: ...

class CreateSessionRequest:
    def __init__(self, app_name: str, user_id: str, session_id: Optional[str] = None) -> None: ...
    def with_state(self, key: str, value: Any) -> CreateSessionRequest: ...

class GetSessionRequest:
    def __init__(self, app_name: str, user_id: str, session_id: str) -> None: ...

# Runner
class Runner:
    def __init__(
        self,
        app_name: str,
        agent: LlmAgent,
        session_service: InMemorySessionService,
        run_config: Optional[RunConfig] = None,
    ) -> None: ...
    async def run(self, user_id: str, session_id: str, message: str) -> List[Event]: ...
    async def run_simple(self, user_id: str, session_id: str, message: str) -> str: ...

async def run_agent(
    agent: LlmAgent,
    message: str,
    user_id: str = "default_user",
    session_id: str = "default_session",
    app_name: str = "adk_app",
) -> str: ...

# Error
class AdkError(Exception):
    message: str
    def __init__(self, message: str) -> None: ...

__version__: str
